### ISSUE TITLE
Create tests for frontend & backend

### ISSUE THREAD

**Issue by nikhilxb** [vizstack/vizstack#13]
Right now we have no tests (unit, integration, or functional). This is bad! Good tests enable faster development and make the project more scalable, and are incredibly worth the investment!

- [ ] VizEngine (unit)
- [ ] Atom package? (unit)
- [ ] React components (unit)
- [ ] Tracked graph outputs match untracked graphs
- [ ] ...?

**Comment by ryanholmdahl** [comment]
This seems mostly targeted at our vz-atom project. We do have tests (via Pytest and Jest) in place now for the Vizstack clients and storybooks for the frontend. We can open a new issue if we want more rigorous testing in the future.
