### ISSUE TITLE
Convert LESS styles from Atom into MUI theme JS object

### ISSUE THREAD

**Issue by nikhilxb** [vizstack/vizstack#17]
Don't want to keep mixing global LESS styles from the `styles` folder with those set in Javascript code (in the theme override object or in individual components).

The LESS stylesheet is defined by Atom, and is used to make interface styles consistent with the rest of the IDE. In addition, this stylesheet's variables change depending on what theme the user has set for Atom.

Idea: Use something like`PreJSS` to convert the compiled LESS into a JS object which can be merged into the theme.

**Comment by ryanholmdahl** [comment]
This is a vz-atom issue.
