### ISSUE TITLE
Massive lag when rendering many viewers in quick succession

### ISSUE THREAD

**Issue by ryanholmdahl** [vizstack/vizstack#46]
The problem could be the re-renders of the canvas that are forced every time a new viewer is created, the expense of reading and writing from the pipe to the Python process on each viewer, or both. One solution is to batch communications from the Python process, limiting the number of re-renders and allowing for potentially more compact communications between the process and the REPL.

**Comment by ryanholmdahl** [comment]
This was written for vz-atom, but is actually still relevant for vz-logger. There's definitely unnecessary re-render issues in core right now, but we should probably make separate issues for those as they present themselves.

**Comment by nikhilxb** [comment]
Transferred to #133
